BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS Users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Cars (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    license_plate TEXT NOT NULL UNIQUE,
    brand TEXT,
    model TEXT,
    vin_number TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Detections (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    license_plate TEXT NOT NULL,
    timestamp TEXT NOT NULL,
    car_id INTEGER,
    FOREIGN KEY (car_id) REFERENCES Cars(id)
);

COMMIT;